import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Import additional fonts if needed
import "./globals.css";

// Initialize fonts
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AdBlue",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${inter.className}`}>{children}</body>
    </html>
  );
}
