import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/Navbar"; // Import the Navbar component
import MouseMovement from "./components/MouseMovement";

// Initialize fonts
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Robert Dumitru",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-primary ${inter.className}`} >
        <Navbar />
        <MouseMovement />
        <main>{children}</main>
      </body>
    </html>
  );
}
