import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/Navbar";
import MouseMovement from "./components/MouseMovement";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Robert Dumitru",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon-32x32.png",
    apple: "/apple-touch-icon.png",
    other: [
      {
        rel: "icon",
        type: "image/png",
        sizes: "16x16",
        url: "/favicon-16x16.png",
      },
      {
        rel: "manifest",
        url: "/site.webmanifest",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-primary ${inter.className}`}>
        <Navbar />
        <MouseMovement />
        <main>{children}</main>
      </body>
    </html>
  );
}
